### ISSUE TITLE
Typo in the code figure on the slot page of the docs

### ISSUE THREAD

**Issue by luv2code** [enhance-dev/enhance-ssr#30]
I apologize if this is the wrong place to file an issue. I just wanted to let you know that I think I found a typo in the docs.
I believe the "slot" code figure on [this page](https://enhance.dev/docs/learn/concepts/html/slots) has a misnamed element. It says `<main-layout>` and I think it should be `<my-layout>` to match the element name in the previous figure.

![image](https://user-images.githubusercontent.com/918935/187815928-994ae085-e7bb-4423-b35b-49ffc4927778.png)

I'm happy to do a PR on mistakes like this; but I don't see the docs in any of the repos (that I looked at.)

**Comment by ryanblock** [comment]
@luv2code thanks, this is a fine place for the issue for now! We haven't yet opened up the enhance.dev repo, but it will be soon.

Just patched this, the fix will be live in a few minutes. Thank you!
