### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by erkannt** [enhance-dev/enhance-ssr#48]
Are there any plans for supporting TypeScript in this library?

**Comment by tbeseda** [comment]
Hi @erkannt 
What would that look like? It doesn't not support TypeScript (or any compiles-to-JS superset syntax).
Do you mean types for the call signatures for the options?

**Comment by erkannt** [comment]
Yes, something that provides the types you mention to allow _enhance_ to be used inside typescript projects easily.
The cleanest would we a `.d.ts` file inside of this repo, but if that goes against the scope of this project I guess there is always the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) escape hatch.

**Comment by kristoferjoseph** [comment]
As Typescript is not a web standard it does not make sense to use in a web standards focused project.

When types become a standard we will support them and avoid all costly and time consuming refactors required to support an ever breaking type system that delivers no user facing benefits.

We respect your time too much to subject you to inevitable breaking changes.

https://enhance.dev/docs/learn/why-enhance

**Comment by erkannt** [comment]
Thanks for clarifying. That choice makes sense to me given your objectives.
