### ISSUE TITLE
Get separate `<head>` and `<body>` serializations

### ISSUE THREAD

**Issue by jaredcwhite** [enhance-dev/enhance-ssr#51]
I've been working on a demo of using the Enhance SSR package directly (aka outside of the framework), and I ran into an issue where the `html` function returned by `enhance` is returning an entire HTML document. In my setup I already have a skeleton HTML template, so all I want is to get the separate head/body pair from the function (thus switching on `bodyContent` won't help me either).

I got a patch working by adding a `separateContent` boolean and returning those serialized values at the end of the `html` function:

```js
    if (separateContent) {
      return {
        head: serialize(head).replace(/__b_\d+/g, ''), // NOTE: I'm not sure what these regexes are for but I copied them up
        body: serialize(body).replace(/__b_\d+/g, '')
      }
    } else {
      return (bodyContent
        ? serializeOuter(body.childNodes[0])
        : serialize(doc))
            .replace(/__b_\d+/g, '')
    }
```

If something like that sounds good to you, I can work on a PR to submit.

**Comment by kristoferjoseph** [comment]
Thanks for asking Jared. 
there is a bodyContent property for getting only the body content. 

Here is an example from the tests of how to use it. 

 https://github.com/enhance-dev/enhance-ssr/blob/d3af6b0d8535a95c277df15941ef610aa3fdb598/test/enhance.test.mjs#L58

**Comment by jaredcwhite** [comment]
@kristoferjoseph This is for the case that Enhance SSR is used to render a fragment of component(s), and it has hoisted styles up into `<head>`…currently there's no way to access those when just using `bodyContent`. If the answer is to use Enhance for complete HTML documents only, and not support an interop scenario with external HTML layout rendering, we can go ahead and close.
