### ISSUE TITLE
Bun and Zig?

### ISSUE THREAD

**Issue by jedisct1** [enhance-dev/enhance-ssr#60]
Hi!

And congrats for Enhance WASM! Looks like a very useful project!

I'm quite surprised to see that Bun is not listed in the listed runtimes, and neither is the Zig language in spite of being one of the most efficient languages for WebAssembly, and being supported by Extism.

Are these supported?

**Comment by kristoferjoseph** [comment]
Anything that is supported by Extism will work.
We don't have any Zig experts on the team but PRs are welcome!
