### ISSUE TITLE
License for Enhance SSR? 

### ISSUE THREAD

**Issue by mdarrik** [enhance-dev/enhance-ssr#74]
Does enhance-ssr have a license for the code/package? It seems likely the license is Apache 2.0 based on [enhance-ssr-wasm](https://github.com/enhance-dev/enhance-ssr-wasm) and [enhance-styles](https://github.com/enhance-dev/enhance-styles), but thought I'd check specifically.

**Comment by macdonst** [comment]
@mdarrik yes, it is Apache-2.0. Github should be surfacing it from here https://github.com/enhance-dev/.github/blob/main/LICENSE
